### ISSUE TITLE
bento mode task list

### ISSUE THREAD

**Issue by estherkim** [estherkim/good-bot#17]
- [ ] Prepare web component build and release to npm for each component 
  - [ ] Export `defineElement` function from `extensions/foo/1.0/dist/web-component.js`. The body of the function can be taken from the CDN build: https://github.com/ampproject/amphtml/blob/626a01ada72328368231db3e0b438528ffd489cf/build-system/compile/compile-wrappers.js#L109-L116 
  - [ ] Update the `package.json` details for the `./` export to go to `./web-component.js` (currently it goes to the `./preact` export)

- [ ] Prepare custom-elements package
  - [ ] Create `@ampproject/custom-elements-polyfill` package
  - [ ] One-time manual publish the current polyfill to the package
  - [ ] Devise a long term plan for propagating repo changes to a release to the package so they stay in sync

- [ ] Document usage of the two packages, ex:
```html
<script async src="my-custom-publisher-script.js>

<bento-foo style="width: 200px; height: 100px" ...></bento-foo>
```
```javascript
// my-custom-publisher-script
import {installCustomElementsPolyfill} from "@ampproject/custom-elements-polyfill";
import {defineElement as defineBentoFooElement} from "@ampproject/foo";

installCustomElementsPolyfill();
defineBentoFooElement();
```
